Этап 2. Основной сервис
EvgeniyBudaev/java-explore-with-me pull request #4
Opened 2023-03-21 04:50 UTC by EvgeniyBudaev

2023-03-23 13:48 UTC, AnastasiyaFomkina requested changes

2023-03-23 13:48 UTC, AnastasiyaFomkina commented on main_svc/src/main/java/ru/practicum/main/services/impl/EventServiceImpl.java
> +        Predicate criteria = builder.conjunction();
Код со строк 196-203 повторяется на строках 246-253. Нужно переписать методы таким образом, чтобы не дублировать общую часть. Например можно добавить флаг, по которому дальше будет определено, как конкретно искать значения

2023-03-23 13:48 UTC, AnastasiyaFomkina commented on main_svc/src/main/java/ru/practicum/main/services/impl/EventServiceImpl.java
> +        requestDto.setApp(nameService);
Код со строк 327-334 повторяется на строках 341-348. Нужно вынести общую часть в отдельный метод

2023-03-23 13:48 UTC, AnastasiyaFomkina commented on stat_svc/stat_server/src/main/java/ru/practicum/server/mappers/ViewStatsMapper.java
> +    ViewStatsDto toDto(ViewStats viewStats);
Ну используется

2023-03-23 15:26 UTC, EvgeniyBudaev commented on main_svc/src/main/java/ru/practicum/main/dto/NewEventDto.java
> +    @Size(min = 3, max = 120)
В checkstyle 120 символов и валидацию не проходит. В ошибке сказано что checkstyle менять нельзя.

2023-03-23 15:31 UTC, EvgeniyBudaev commented on main_svc/src/main/java/ru/practicum/main/dto/NewEventDto.java
> +    @Size(min = 20, max = 2000)
Это всё очень условно. В техническом задании нет конкретных чисел.

2023-03-23 15:32 UTC, EvgeniyBudaev commented on main_svc/src/main/java/ru/practicum/main/dto/NewEventDto.java
> +    @Size(min = 20, max = 2000)
По диапазону требуется проработка аналитика со стороны яндекс-практикума

2023-03-23 15:40 UTC, EvgeniyBudaev commented on main_svc/src/main/java/ru/practicum/main/dto/NewEventDto.java
> +    @Size(min = 20, max = 2000)
Здесь валидатор  принял изменения.  Такое лучше согласовывать с командой по разработке задания.

2023-03-24 05:45 UTC, EvgeniyBudaev commented on stat_svc/stat_server/src/main/java/ru/practicum/server/mappers/ViewStatsMapper.java
> +    ViewStatsDto toDto(ViewStats viewStats);
Поправил

2023-03-24 05:45 UTC, EvgeniyBudaev commented on stat_svc/stat_client/src/main/java/ru/practicum/client/StatClient.java
> +            throw new RuntimeException(e);
Выбросил свое исключение

2023-03-24 05:45 UTC, EvgeniyBudaev commented on stat_svc/stat_client/src/main/java/ru/practicum/client/StatClient.java
> +            array = objectMapper.readValue(response.getBody(), ViewStatsDto[].class);
Поправил

2023-03-24 05:46 UTC, EvgeniyBudaev commented on main_svc/src/main/java/ru/practicum/main/dto/CategoryDto.java
Добавил

2023-03-24 05:46 UTC, EvgeniyBudaev commented on main_svc/src/main/java/ru/practicum/main/dto/EventFullDto.java
> +    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
Вынес патерн

2023-03-24 05:47 UTC, EvgeniyBudaev commented on stats/stats-client/src/main/java/ru/practicum/client/BaseClient.java
p.s. "Чтобы построить что-то новое, нужно снести что-то старое - такова цена прогресса".

2023-03-24 14:24 UTC, EvgeniyBudaev commented on stat_svc/stat_client/src/main/java/ru/practicum/client/StatClient.java
> +    private final String serverUrl = "http://stats-server:9090";
Поправил

2023-03-25 07:01 UTC, AnastasiyaFomkina commented on main_svc/src/main/java/ru/practicum/main/dto/NewEventDto.java
> +    @Size(min = 3, max = 120)
Как-то упустила этот момент, спасибо

2023-03-25 07:04 UTC, AnastasiyaFomkina approved these changes

2023-03-25 07:14 UTC, merged