Этап 3. Дополнительная функциональность
EvgeniyBudaev/java-explore-with-me pull request #5
Opened 2023-03-25 08:13 UTC by EvgeniyBudaev

2023-03-26 10:37 UTC, AnastasiyaFomkina requested changes
Отличная работа 👍 Оставила нескольких небольших комментариев

2023-03-26 10:37 UTC, AnastasiyaFomkina commented on README.md
Нужно расширить readme. Кратно описать проект, добавить схемы бд и основные endpoint'ы

2023-03-26 10:37 UTC, AnastasiyaFomkina commented on main_svc/src/main/java/ru/practicum/main/controllers/priv/PrivateCommentController.java
> +                                                        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
Нужно использовать константу `DATE`

2023-03-26 10:37 UTC, AnastasiyaFomkina commented on main_svc/src/main/java/ru/practicum/main/controllers/priv/PrivateCommentController.java
> +                                                        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
Нужно использовать константу `DATE`

2023-03-26 10:37 UTC, AnastasiyaFomkina commented on main_svc/src/main/java/ru/practicum/main/repositories/CommentsRepository.java
> +    Page<Comment> findAllByEvent_Id(Long eventId, Pageable pageable);
Нужно сразу возвращать `List`, тогда не придется кастовать `Page` к списку в сервисе.

2023-03-26 10:37 UTC, AnastasiyaFomkina commented on main_svc/src/main/java/ru/practicum/main/controllers/admin/AdminCommentController.java
> +import org.springframework.web.bind.annotation.*;
Давай избавимся от [wildcard](https://struchkov.dev/blog/using-wildcard-imports-in-java/) в импортах

2023-03-26 11:20 UTC, EvgeniyBudaev commented on main_svc/src/main/java/ru/practicum/main/controllers/priv/PrivateCommentController.java
> +                                                        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
Поправил

2023-03-26 11:20 UTC, EvgeniyBudaev commented on main_svc/src/main/java/ru/practicum/main/controllers/priv/PrivateCommentController.java
> +                                                        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
Поправил

2023-03-26 11:37 UTC, EvgeniyBudaev commented on main_svc/src/main/java/ru/practicum/main/controllers/admin/AdminCommentController.java
> +import org.springframework.web.bind.annotation.*;
Избавился от wildcard в импортах

2023-03-26 12:11 UTC, EvgeniyBudaev commented on main_svc/src/main/java/ru/practicum/main/repositories/CommentsRepository.java
> +    Page<Comment> findAllByEvent_Id(Long eventId, Pageable pageable);
Поправил

2023-03-28 07:43 UTC, afomkina approved these changes

2023-03-28 15:28 UTC, merged